[requirement]
min_version = [0, 43, 1]

[general]
reload_config_each_move = false
clear_hash_after_config_loaded = false
default_thread_num = 0
message_mode = "normal"
coord_conversion_mode = "none"
default_candidate_range = "square3_line4"
memory_reserved_mb = 64
default_tt_size_kb = 262144

[model]
binary_file = "model210901.bin"

[model.evaluator]
type = "mix9svq"
draw_black_winrate = 0.5
draw_ratio = 1.0

[[model.evaluator.weights]]
weight_file = "mix9svqfreestyle_bsmix.bin.lz4"
[[model.evaluator.weights]]
weight_file = "mix9svqstandard_bs15.bin.lz4"
[[model.evaluator.weights]]
weight_file_black = "mix9svqrenju_bs15_black.bin.lz4"
weight_file_white = "mix9svqrenju_bs15_white.bin.lz4"

[search]
aspiration_window = true
num_iteration_after_mate = 32
num_iteration_after_singular_root = 32
max_search_depth = 200

[search.timectl]
match_space = 30.0
match_space_min = 10.0
average_branch_factor = 1.7
advanced_stop_ratio = 0.95
move_horizon = 64

[database]
enable_by_default = true
type = "yixindb"
url = "rapfi.db"

[database.yixindb]
compressed_save = true
save_on_close = true
num_backups_on_save = 3
ignore_corrupted = true

[database.search]
readonly_mode = false
query_ply = 2
pv_iter_per_ply_increment = 1
nonpv_iter_per_ply_increment = 2
pv_write_ply = 4
pv_write_min_depth = 20
write_value_range = 1000
mate_write_ply = 6
mate_write_min_depth_exact = 0
mate_write_min_depth_nonexact = 0
mate_write_min_step = 0
exact_overwrite_ply = 100
nonexact_overwrite_ply = 0
overwrite_rule = "better_value_depth_bound"
overwrite_exact_bias = 4
overwrite_depth_bound_bias = -1
query_result_depth_bound_bias = 0

[database.libfile]
black_win_mark = "a"
white_win_mark = "c"
black_lose_mark = "c"
white_lose_mark = "a"
ignore_comment = false
